# Generated by Django 4.2.7 on 2025-09-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_user_id_0c526b_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_user_id_3fa5de_idx',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_done'], name='tasks_task_is_done_c180e8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='tasks_task_categor_451d6a_idx'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
